//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardTradingDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.PriceLists = new HashSet<PriceList>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string ChineseName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public int PaymentType { get; set; }
        public int PrintMethod { get; set; }
        public bool IsDelayPrinted { get; set; }
        public bool IsEstimated { get; set; }
        public int BillingType { get; set; }
        public bool IsRecorded { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual BillingType BillingType1 { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual ICollection<PriceList> PriceLists { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
